[package]
name = "libcw"
version = "1.0.0"
authors = ["Altair Bueno"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "cw core library for fast and reliable count"
repository = "https://github.com/Altair-Bueno/cw"
keywords = ["wc","cw","word","line","character","UTF8","UTF16","count"]
categories = ["filesystem","text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
