name: Performance metrics
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Benchmark
        run: |
          echo "Install dependencies"
          cargo install --path .
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
          sudo dpkg -i hyperfine_1.11.0_amd64.deb

          echo "Fetch CPU & version data"
          cat /proc/cpuinfo > $GITHUB_WORKSPACE/bench/cpuinfo.txt
          echo "Hyperfine version: $(hyperfine --version)" > $GITHUB_WORKSPACE/bench/version.txt
          echo "gwc version: $(wc --version)" >> $GITHUB_WORKSPACE/bench/version.txt
          echo "cw version: $(cw --version)" >> $GITHUB_WORKSPACE/bench/version.txt

          echo "Running benchmark"
          $GITHUB_WORKSPACE/bench/bench.sh > $GITHUB_WORKSPACE/bench/stats.txt

      - name: Upload results
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add --all
          git commit -am "Benchmark finished"
          git push
