name: Build release artifacts
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        target:
          # Linux
          - "x86_64-unknown-linux-musl"
          # macOS Apple Silicon
          - "aarch64-apple-darwin"
          # macOS Intel
          - "x86_64-apple-darwin"
          # Windows Intel x64
          - "x86_64-pc-windows-gnu"
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ matrix.target }}
      MACOSX_DEPLOYMENT_TARGET: 11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # - if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
      #   name: Set up MinGW
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x64
      - name: Set up target ${{ matrix.target }}
        run: |
          rustup toolchain install stable-${{ matrix.target }}
          rustup target add $TARGET
      - name: Build binary for target ${{ matrix.target }}
        run: cargo build --release --target "$TARGET"
      - uses: actions/upload-artifact@v2
        with:
          name: cw-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/cw