name: Build release artifacts
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        target:
          # Linux
          - "x86_64-unknown-linux-gnu"
          # macOS Apple Silicon
          - "aarch64-apple-darwin"
          # macOS Intel
          - "x86_64-apple-darwin"
          # Windows Intel x64
          - "x86_64-pc-windows-gnu"
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ matrix.target }}
      MACOSX_DEPLOYMENT_TARGET: 11.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up target ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: ${{ matrix.target }}

      - name: Build binary for target ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: cw-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/cw