name: Build macOS Apple Silicon
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
    MACOSX_DEPLOYMENT_TARGET: 11.0
    TARGET: aarch64-apple-darwin

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup target add $TARGET
          cargo build --release --target $TARGET
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: cw_macos_aarch64
          path: |
            target/$TARGET/release/cw