name: Performance metrics
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install hyperfine
        continue-on-error: true
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
          sudo dpkg -i hyperfine_1.11.0_amd64.deb

      - uses: actions/checkout@v2
      - name: System info
        run: |
          echo "System info" > Stats.txt
          cat /proc/cpuinfo >> Stats.txt

      - name: build & install
        run: cargo install --path .

      - name: Benchmark
        run: |
          echo $(where hyperfine)
          echo "Tests" >> Stats.txt
          hyperfine -m 100 -w 2 "cw -wlb $(ls | xargs)" "wc -wlc $(ls | xargs)" >> Stats.txt

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Stats
          path: Stats.txt
          retention-days: 5