name: Unit tests
on:
  push:
    branches: [ dev, 'feat/*', 'doc/*' ]
  pull_request:
    branches: [ '*' ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  libcwtest:
    name: |
      name: cargo unit test
      os: ${{ matrix.os }}
      features: ${{ matrix.features }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", 'windows-latest', 'macos-latest' ]
        features: [ " ", "anymap", "serde", "clap", "tower" ]

    steps:
      - name: Disable autocrlf
        run: git config --global core.autocrlf false
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v2
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Test
        run: cargo test "--features=${{ matrix.features }}"
        working-directory: crates/libcw
